### ISSUE TITLE
Assertionerror

### ISSUE THREAD

**Issue by coppensb** [basilfx/homeassistant-biketrax#23] opened 2022-09-05 10:40 UTC
Dear,
This integration stopped working as of yesterday and I am now receiving following messages in the logs:

This error originated from a custom integration.

Logger: custom_components.biketrax.coordinator
Source: custom_components/biketrax/coordinator.py:111
Integration: PowUnity BikeTrax (documentation, issues)
First occurred: 12:33:25 PM (2 occurrences)
Last logged: 12:33:29 PM

Unexpected error fetching biketrax-xxx@xxxx.com-subscription data:
Traceback (most recent call last):
  File "/srv/homeassistant3.9_1/lib/python3.9/site-packages/homeassistant/helpers/update_coordinator.py", line 205, in _async_refresh
    self.data = await self._async_update_data()
  File "/home/homeassistant/.homeassistant/custom_components/biketrax/coordinator.py", line 111, in _async_update_data
    await device.update_subscription()
  File "/srv/homeassistant3.9_1/lib/python3.9/site-packages/aiobiketrax/client.py", line 184, in update_subscription
    ] = await self._account.admin_api.get_subscription(self._device.unique_id)
  File "/srv/homeassistant3.9_1/lib/python3.9/site-packages/aiobiketrax/api.py", line 424, in get_subscription
    return models.subscription_from_dict(response)
  File "/srv/homeassistant3.9_1/lib/python3.9/site-packages/aiobiketrax/models.py", line 802, in subscription_from_dict
    return Subscription.from_dict(s)
  File "/srv/homeassistant3.9_1/lib/python3.9/site-packages/aiobiketrax/models.py", line 611, in from_dict
    setup_fee = from_none(obj.get("setupFee"))
  File "/srv/homeassistant3.9_1/lib/python3.9/site-packages/aiobiketrax/models.py", line 13, in from_none
    assert x is None
AssertionError

I have tried to re-install the custom integration but no success. I am running Home Assistant 2022.8.5 core with latest biketrax version 2.1.0 with Python 3.9.1. All dependencies seems well installed.

**Comment by basilfx** [comment] 2022-09-05 12:36
Thanks for reporting. This is probably a [known issue](https://github.com/basilfx/aiobiketrax#known-issues) and easy to fix.

Can you send me some example responses of the subscription related calls? The easiest way is to use the browser app, and is the network tab of Chrome/Safari/etc to log the API calls.

Also, did it stop working suddenly, or is it (by any chance) related to a renewed subscription or expired trial?

**Comment by coppensb** [comment] 2022-09-05 18:14
You are spot on, it stopped working after going from an expired trial plan to a yearly plan (and this after my previous yearly plan expired).
My subscription still seems to be in trial dough I paid for a yearly plan just some days ago. Looks like a bug in Poweunity/biketrax. 
Just for testing purposes , I changed my plan today to monthly but that did not help either
Here below a console capture from the app, hope it helps. Note that I anonymized id info and IP address

subscription: Object { id: "xxxxxxxxxx", plan_id: "biketrax-service-plan-1m", plan_quantity: 1, … }
​​
billing_period: 1
​​
billing_period_unit: "month"
​​
cf_device_id:  xxxxxxxx
​​
channel: "web"
​​
created_at: 1662383713
​​
created_from_ip: "x.x;.x;.x"
​​
currency_code: "EUR"
​​
customer_id: "ABCDEF"
​​
deleted: false
​​
due_invoices_count: 0
​​
has_scheduled_advance_invoices: false
​​
has_scheduled_changes: false
​​
id: "ABCDEF"
​​
next_billing_at: 1693741745
​​
object: "subscription"
​​
plan_amount: 395
​​
plan_free_quantity: 0
​​
plan_id: "biketrax-service-plan-1m"
​​
plan_quantity: 1
​​
plan_unit_price: 395
​​
resource_version: 1662383713909
​​
started_at: 1662383713
​​
status: "in_trial"
​​
trial_end: 1693741745
​​
trial_start: 1662383713
​​
updated_at: 1662383713
​​
Please let me know if you need anything else. Thank you

**Comment by coppensb** [comment] 2022-09-05 18:19
this is a snapshot from the app. Looks like I have a free plan for which I paid 39.5Euro..... :-)

![image](https://user-images.githubusercontent.com/79207968/188499814-b9bfd6df-d568-4af4-973d-72fa93b28dc4.png)

**Comment by coppensb** [comment] 2022-09-05 18:27
Sorry there is another object which I forgot to copy/paste
![image](https://user-images.githubusercontent.com/79207968/188500321-f7f05b2a-7d0b-4b31-9e30-34d51504451d.png)

**Comment by basilfx** [comment] 2022-09-07 06:05
Is this from `subscriptions/<unique_id>` API call? Lots of new properties I don't have. I would expect a `setup_fee` property, but that one is missing here.

**Comment by basilfx** [comment] 2022-09-07 06:06
For reference: https://github.com/basilfx/aiobiketrax/blob/master/aiobiketrax/models.py#L594

**Comment by basilfx** [comment] 2022-09-12 09:34
@coppensb Can you confirm if any of the responses is of the `https://admin.powunity.com/api/subscriptions/<subscription_id>` API call?

**Comment by coppensb** [comment] 2022-09-13 13:48
This was taken using the desktop frontend app.

**Comment by basilfx** [comment] 2022-09-15 20:49
I double checked, but the examples you provided don't seem from the `https://admin.powunity.com/api/subscriptions/<subscription_id>` call. It is invoked if you go to the license settings on the settings page, in the app. The response should like something like [this](https://github.com/basilfx/aiobiketrax/blob/master/contrib/responses/subscription.json) file.

Either the `setupFee` is not required, or it is an integer, string, boolean. That's what I need to know to fix it.

My tracker still has a trial period, and it takes another 260 days before I need a license 😅.

**Comment by basilfx** [comment] 2022-09-15 20:50
If you have access to the files, you can also try to change [this](https://github.com/basilfx/aiobiketrax/blob/master/aiobiketrax/api.py#L18) variable to True, to see the actual API responses.

**Comment by pupe666** [comment] 2022-09-18 21:39
I reported a duplicate of this problem, sorry for that.

I just installed the integration. And I have a monthly subscription..

Let me know if I can help in any way. I'm not a coder, but if you want some one to test a new release, just let me know.

**Comment by basilfx** [comment] 2022-09-19 06:27
@pupe666 It would help if you could show me the response of the `https://admin.powunity.com/api/subscriptions/<subscription_id>` API call, so I know how it looks like for paying users. 

You can trigger this request by visiting the subscription settings in the browser app.

**Comment by pupe666** [comment] 2022-09-19 07:32
This is what it looks lite for me
`{"trialEnd":"2022-10-02T16:26:40.000Z","subscriptionId":"AzqSEGTFqCIyOFFcO","category":"B2C","trialDuration":365,"setupFee":false,"id":19684,"createdAt":"2021-02-01T13:06:35.000Z","updatedAt":"2022-09-02T16:26:53.000Z","uniqueId":"4710195114"}`

**Comment by basilfx** [comment] 2022-09-19 07:37
@pupe666 Thanks. That's what I needed.

**Comment by basilfx** [comment] 2022-09-19 07:46
I have included a fix for this issue in the latest master version of [aiobiketrax](https://github.com/basilfx/aiobiketrax).

Can you see if this version works? You can install a newer version using the following instructions: https://github.com/basilfx/homeassistant-biketrax#development-version.

**Comment by basilfx** [comment] 2022-09-19 11:47
@pupe666 Not sure what happened here. The log message looks strange to me: it complains about a backup template, which has nothing to do with this integration.

Removing the old version depends on your method of installation. If you have Home Assistant OS, then install the terminal to access the system. If you have Home Assistant Core, then enter the virtual environment to remove the plugin.

I don't use Home Assistant OS, but I found the following steps [here](https://community.home-assistant.io/t/execute-in-home-assistant-container-context/415031/3):

```
* Turn on advanced mode for your user (if you don’t have that turned on already)
* Install the [SSH & Web Terminal addon 7](https://my.home-assistant.io/redirect/supervisor_addon/?addon=a0d7b954_ssh) (the one in community add-ons not the official one)
* Disable protection mode on the ssh add-on and start it
* While ssh’ed (or from the [web terminal](https://my.home-assistant.io/redirect/supervisor_ingress/?addon=a0d7b954_ssh)) enter docker exec -it homeassistant bash
* Do whatever command you’re trying to test, you’re now in the HA container
```

**Comment by pupe666** [comment] 2022-09-19 11:55
Sorry for the wrong logs, a bit stressed to do this on my lunch.

I'll try the SSH thingy tonight. I'll let you know how it goes.

Thanks

**Comment by pupe666** [comment] 2022-09-19 15:16
Hello. 
Tried to follow these steps
* Turn on advanced mode for your user (if you don’t have that turned on already)
* Install the [SSH & Web Terminal addon 7](https://my.home-assistant.io/redirect/supervisor_addon/?addon=a0d7b954_ssh) (the one in community add-ons not the official one)
* Disable protection mode on the ssh add-on and start it
* While ssh’ed (or from the [web terminal](https://my.home-assistant.io/redirect/supervisor_ingress/?addon=a0d7b954_ssh)) enter docker exec -it homeassistant bash
* Do whatever command you’re trying to test, you’re now in the HA container

But it looks like the addon crashes as soon it is started. I tried with the "built-in" SSH plugin. But that one is missing the option to disable protection mode. Tried to google some other way to do it. But thats way above my knowledge in Linux and docker, so I have to give up before i do something stupid and crashes my HA installation.
Sorry for that.

Hope someone else can be a better of assistance.

**Comment by basilfx** [comment] 2022-10-04 22:05
I will try to release an alpha version with this fix included. It should also include additional logging to solve similar issues.

**Comment by basilfx** [comment] 2022-10-04 22:45
Version 0.2.2a1 includes this fix. You can install the pre-release version using the HACS beta repository feature (https://hacs.xyz/docs/faq/beta/).

If it does not work, then please enable debug logging (see the README.md), and provide the relevant logs.

**Comment by coppensb** [comment] 2022-10-05 08:59
This version works for me. The assertion error is gone and all my entities are appearing well, including the "subscription"until" entity. Thank you very much Bas for resolving this issue.

**Comment by basilfx** [comment] 2022-10-05 10:28
Thanks for letting me know. I’ll release a proper 0.2.2 once ready. Will close this one for now.

**Closed by basilfx** 2022-10-05 10:28 UTC
