### ISSUE TITLE
Unknown error while login

### ISSUE THREAD

**Issue by corincorvus** [basilfx/homeassistant-biketrax#119] opened 2024-05-08 16:01 UTC
Hi,

Today my Integration are gone. The Service is not available and if i delete the Integration and try to relogin i only get an unknown error.

I didnt find useful logs.

The Account work in powunity App.

What do you need from me? 

Thanks

**Comment by corincorvus** [comment] 2024-05-08 16:23
Log

```
Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: custom_components.biketrax.config_flow
Quelle: custom_components/biketrax/config_flow.py:77
Integration: biketrax (Dokumentation, Probleme)
Erstmals aufgetreten: 18:13:11 (1 Vorkommnisse)
Zuletzt protokolliert: 18:13:11

Unexpected exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/aiobiketrax/api.py", line 49, in wrapper
    return await func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiobiketrax/api.py", line 220, in get_devices
    return [models.device_from_dict(device) for device in response]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiobiketrax/models.py", line 871, in device_from_dict
    return Device.from_dict(s)
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiobiketrax/models.py", line 627, in from_dict
    geofence_ids = from_list(lambda x: x, obj.get("geofenceIds"))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiobiketrax/models.py", line 34, in from_list
    assert isinstance(x, list)
AssertionError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/biketrax/config_flow.py", line 77, in async_step_user
    info = await validate_input(self.hass, user_input)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/biketrax/config_flow.py", line 41, in validate_input
    await account.update_devices()
  File "/usr/local/lib/python3.12/site-packages/aiobiketrax/client.py", line 61, in update_devices
    device.id: device for device in await self.traccar_api.get_devices()
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiobiketrax/api.py", line 51, in wrapper
    raise ApiError("Unable to parse API response.") from e
aiobiketrax.exceptions.ApiError: Unable to parse API response. 
```

**Comment by pupe666** [comment] 2024-05-08 20:12
Mybint

**Comment by pupe666** [comment] 2024-05-08 20:16
My integration is still there but everything is unavailable. Could it relate to the same issue? Not sure what logs that are relevant. I Janebrink gott sant errors or warnings after HA reboot.

![Screenshot_20240508-221234](https://github.com/basilfx/homeassistant-biketrax/assets/97130254/92404f98-6363-4a80-a266-7e10b6675043)

**Comment by corincorvus** [comment] 2024-05-08 20:18
> My integration is still there but everything is unavailable. Could it relate to the same issue? Not sure what logs that are relevant. I Janebrink gott sant errors or warnings after HA reboot.
> 
> ![Screenshot_20240508-221234](https://private-user-images.githubusercontent.com/97130254/329035127-92404f98-6363-4a80-a266-7e10b6675043.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUxOTk3NTcsIm5iZiI6MTcxNTE5OTQ1NywicGF0aCI6Ii85NzEzMDI1NC8zMjkwMzUxMjctOTI0MDRmOTgtNjM2My00YTgwLWEyNjYtN2UxMGI2Njc1MDQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA4VDIwMTczN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBlODQ3MzQ0M2NjNGFjNWM2NjBkODZjZDMwZTNjYTkyOTlkOGY4OTQzMmZkMWJmMjNjMWY4ZWZmZGU4NzRmNzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mvrmXXmmtadmwZq7w8PxplNkkKLwPe8WB4LDsi3MLIw)

My Integration was also not available. Cause the problem i removed the configuration and want to relogin. now i stuck.

**Comment by pupe666** [comment] 2024-05-08 20:25
@basilfx let me know if you want any logs from me.

**Comment by pupe666** [comment] 2024-05-08 20:36
After last reboot i got this error. Dont think i had it before.
![Screenshot_20240508-223337](https://github.com/basilfx/homeassistant-biketrax/assets/97130254/23e4f8ee-b15b-4fcb-8c39-4f23b7394575)

**Comment by FlorianWilk** [comment] 2024-05-08 21:41
Same here, Integration worked for a long time without any issues.
Today at 10:42 everyit became unavailable. 

![image](https://github.com/basilfx/homeassistant-biketrax/assets/3532286/46a0f4f0-8d1d-4208-83de-a53457684d9b)

Now it says: A BikeTrax error occured while updating the devices: Unable to parse API response

since your integration didn't change, i guess they changed the API?

**Comment by gyusza** [comment] 2024-05-08 22:22
Seems like the ID from the API is expected as a string, but returned as an integer:

<img width="1116" alt="image" src="https://github.com/basilfx/homeassistant-biketrax/assets/8712275/f9205302-5264-4be1-816d-18b6e6edf687">

vs the API call:

<img width="1095" alt="image" src="https://github.com/basilfx/homeassistant-biketrax/assets/8712275/a3b8bd27-4906-4b66-97c3-aaf131654236">

**Comment by vlebourl** [comment] 2024-05-10 09:06
> Seems like the ID from the API is expected as a string, but returned as an integer:
> 
> <img alt="image" width="1116" src="https://private-user-images.githubusercontent.com/8712275/329070895-f9205302-5264-4be1-816d-18b6e6edf687.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzMzIwNzYsIm5iZiI6MTcxNTMzMTc3NiwicGF0aCI6Ii84NzEyMjc1LzMyOTA3MDg5NS1mOTIwNTMwMi01MjY0LTRiZTEtODE2ZC0xOGI2ZTZlZGY2ODcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUxMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MTBUMDkwMjU2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODc2YTAyOTE0ZTI1ZDMyYTY5NzI3N2RmOTg1ZTIxNjJmZDFjNWMyZTdlNzdiYTRhZmI3ZGNmMmRjYTQxMGVhZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.gACH0sQbKtnF-f6zasQyIkcvJ2Hs9dJ5GevCG4_fDLE">
> vs the API call:
> 
> <img alt="image" width="1095" src="https://private-user-images.githubusercontent.com/8712275/329071219-a3b8bd27-4906-4b66-97c3-aaf131654236.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzMzIwNzYsIm5iZiI6MTcxNTMzMTc3NiwicGF0aCI6Ii84NzEyMjc1LzMyOTA3MTIxOS1hM2I4YmQyNy00OTA2LTRiNjYtOTdjMy1hYWYxMzE2NTQyMzYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUxMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MTBUMDkwMjU2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZGJmNDVhZjVlNTc0ZTU4NDkzOTQ4M2JmNjNiNzYwYTE3MmZjYzU5M2ViYTY3ZTFlNjM4ZTQ0MDFlZDkxYmE2ZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.m12P7lsh_Z4Ln-2eCTTpbsW7l2Xt5oIkAfsJ3nFd7X8">

Although this should be fixed indeed, this should not impact the integration too much, and is not the reason why the integration seems broken at the moment. See https://github.com/home-assistant/core/issues/116165 for a similar bug. 

Regarding this issue, on my side I get this: 
![image](https://github.com/basilfx/homeassistant-biketrax/assets/5701372/94ea2597-264e-4b29-a12b-e25a93cb2d0a)

I'm investigating and will try to propose a patch when fixed.

**Comment by basilfx** [comment] 2024-05-10 12:50
Thank you for the reports. I have created a fix [here](https://github.com/basilfx/aiobiketrax/pull/99)., which I just merged into `aiobiketrax`.

There are multiple ways to test this fix, depending on how you run HASS. See the [README.md](https://github.com/basilfx/homeassistant-biketrax?tab=readme-ov-file#development-version) for more information, or wait until I released a new version.

**Comment by corincorvus** [comment] 2024-05-10 12:54
> Thank you for reporting this issue. I have created a fix [here](https://github.com/basilfx/aiobiketrax/pull/99)., which I just merged into `aiobiketrax`.
> 
> There are multiple ways to test this fix, depending on how you run HASS. See the [README.md](https://github.com/basilfx/homeassistant-biketrax?tab=readme-ov-file#development-version) for more information, or wait until I released a new version.

Thank you for resolving the Issue!

**Comment by vlebourl** [comment] 2024-05-10 13:58
I can confirm the fix works! Thanks for the reactivity :)

**Comment by corincorvus** [comment] 2024-05-10 14:43
How long is the time to update it in HACS?

**Comment by vlebourl** [comment] 2024-05-13 14:26
> Today the update is not available in HACS :/
it's not yet released, see here: https://github.com/basilfx/homeassistant-biketrax/issues/119#issuecomment-2104555214

you can force the use of the dev version with this: https://github.com/basilfx/homeassistant-biketrax?tab=readme-ov-file#development-version

**Comment by basilfx** [comment] 2024-05-21 21:10
v2.0.0 is out. After a week of testing, I did not encounter any issues.

**Closed by basilfx** 2024-05-21 21:10 UTC
